Stupid ribbon created error, now fixed by display: none
Commenting the <jhi-page-ribbon></jhi-page-ribbon> away caused:
TypeError: Cannot read property 'identity' of undefined

Very weird